# Generated by Django 3.1.3 on 2021-03-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Architekt', '0002_auto_20210324_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adres',
        ),
        migrations.RemoveField(
            model_name='user',
            name='adres2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='data_ur',
        ),
        migrations.RemoveField(
            model_name='user',
            name='imie',
        ),
        migrations.RemoveField(
            model_name='user',
            name='login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nazwisko',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nr_tel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nr_tel2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='projekty',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
