# Generated by Django 3.1.3 on 2021-03-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Architekt', '0003_auto_20210329_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imie',
            field=models.CharField(default='X', max_length=100, verbose_name='Imię'),
            preserve_default=False,
        ),
    ]
