# Generated by Django 3.1.3 on 2021-03-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Architekt', '0004_user_imie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adres',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='adres2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='data_ur',
            field=models.DateField(blank=True, null=True, verbose_name='Data urodzenia'),
        ),
        migrations.AddField(
            model_name='user',
            name='nazwisko',
            field=models.CharField(default='Y', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nr_tel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='nr_tel2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='projekty',
            field=models.TextField(default='Budynek'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
