# Generated by Django 3.1.3 on 2021-04-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Architekt', '0005_auto_20210330_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projekt',
            name='grafika',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
