# Generated by Django 3.1.3 on 2021-05-05 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Architekt', '0006_auto_20210401_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adres',
        ),
        migrations.RemoveField(
            model_name='user',
            name='adres2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nr_tel',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nr_tel2',
        ),
        migrations.AlterField(
            model_name='projekt',
            name='architekt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='projekty',
            field=models.TextField(blank=True),
        ),
    ]
